= Rapport d’avancement du groupe “x.y”
PACT groupe xy (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Groupe 6.3 »

=== Membres du groupe

* Martin Chavaran
* Amine Mirhom
* Romain Darous
* Jonathan Guérin
* Alex Phimanesone
* Pauline Escavi

=== Tuteur

* Laurent Sauvage

=== Encadrant génie logiciel

* Yuan Yao

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Notre projet consiste à détecter les maladies des plantes en les prenant en photo. Lorsque l'utilisateur, qu'il soit un agriculteur, un jardinier, ou un particulier, remarque une plante qui lui paraît malade, il prend en photo une de ses feuilles (certaines conditions de prise de photo seront à respecter pour garantir la meilleure précision possible). L’application lui indique dans un second temps si la plante est malade et le cas échéant de quelle maladie il s’agit.

Des solutions de soins pour les plantes seront ensuite proposées: des tutos, des produits et des contacts d’expert dans le cas d’insuffisance des soins.

Notre projet participe à réponse à la question : "Comment explorer, découvrir et profiter de la nature sans lui nuire ?". L'agriculture exploite les ressources naturelles à grande échelle. Détecter les maladies des plantes et être capable de les traiter permet d'en prendre soin en limitant l'usage de pesticides qui sont nocifs pour l'environnement.



== English Summary (PAN1)

*_Note : 15 lignes max, version anglaise du texte précédent_*

Our project consists in detecting plant diseases by taking pictures of them. When the user, whether he is a farmer, a gardener or a private individual, notices a plant that looks sick, he takes a picture of one of its leaves (certain conditions for taking pictures will be required to ensure the best accuracy possible). Secondly, the app indicates if the plant is sick and if so, which disease it is.

Care solutions for plants will be then suggested : tutorials, products and expert contacts in case of insufficient care.

Our project participates in answering the question : "How to explore, discover and take advantage of the nature without damaging it ?". Agriculture exploits natural resources on a large scale. Detecting plant diseases and being able to treat them allows taking care of them while limiting the use of pesticides that are detrimental to the environment.


////
*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autres:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
différents fichiers) se trouve dans le fichier courant.

**Prenez le temps** de supprimer le texte de remplissage et les sections non
utilisées pour l'instant. Vous pouvez par exemple commenter ces parties non
utilisées pour qu'elles n'apparaissent pas dans le document final. En Asciidoc,
il suffit de les précéder de deux slashs (`//`).
////


// en PDF on ne peut pas controler la position de la toc
// Macros non supportées

////
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]
////


// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
