=== Scénarios d’usage

Mettre ici le scénario d’usage que vous avez construit lors des séances
encadrées par les experts SES. Vous pouvez mettre un scénario amélioré
(et non celui noté) si vous jugez votre scénario insuffisant pour faire
comprendre au jury PACT les différentes étapes d’utilisation de votre
produit/service ou si vous avez changé d’idées entre-temps.

==== 

Bertrand, au cours de son inspection journalière, repère dans son champ un
plant de tomate lui paraissant légèrement anormal. Il n’est pas sûr que la plante
soit malade et ne sait pas quoi faire. Il utilise alors l’application sur son smartphone. Il place une
feuille de papier blanche derrière l’une des feuilles du plant malade. Il prend en
photo la feuille de tomate et l’application lui indique : « le plant est infecté par le
virus de la mosaïque de la tomate! ».

Bertrand se sent perdu face à cette maladie encore inconnue. Mais
l’application lui propose des solutions: un tutoriel écrit pour soigner soi-même la
plante, un historique des maladies qu'il a pu rencontrer, des produits pour soigner la plante et enfin une option pour appeler des
techniciens spécialisés et situés à proximité de chez lui.

==== 
Grâce à l'application, Bertrand a pu éviter de perdre une partie de son exploitation agricole à cause du « virus de la mosaïque ». Il n'a alors pas du utiliser des pesticides, nuisibles à l'environnement et a alors limité ses pertes agricoles.
