=== Scénarios d’usage

Mettre ici le scénario d’usage que vous avez construit lors des séances
encadrées par les experts SES. Vous pouvez mettre un scénario amélioré
(et non celui noté) si vous jugez votre scénario insuffisant pour faire
comprendre au jury PACT les différentes étapes d’utilisation de votre
produit/service ou si vous avez changé d’idées entre-temps.

==== XX

Nulla. Curabitur aliquet leo ac massa. Praesent posuere lectus vitae
odio. Donec imperdiet urna vel ante. In semper accumsan diam. Vestibulum
porta justo. Suspendisse egestas commodo eros.

Suspendisse tincidunt mi vel metus. Vivamus non urna in nisi gravida
congue. Aenean semper orci a eros. Praesent dictum. Maecenas pharetra
odio ut dui. Pellentesque.

==== YY

Ac mauris.

Duis velit magna, scelerisque vitae, varius ut, aliquam vel, justo.
Proin ac augue. Nullam auctor lectus vitae arcu. Vestibulum porta justo
placerat purus. Ut sem nunc, vestibulum nec, sodales vitae, vehicula
eget, ipsum. Sed nec tortor. Aenean malesuada. Nunc convallis, massa eu
vestibulum commodo, quam mauris interdum arcu, at pellentesque.
